spring.application.name=backend
server.port=8081

spring.mongodb.uri=mongodb+srv://onatadeabdulmajeed_db_user:Olaseni12@cluster0.3r9xzlp.mongodb.net/?appName=Cluster0
spring.mongodb.database=verifund

spring.docker.compose.enabled=false


monnify.base.url=https://sandbox.monnify.com
monnify.api-key=MK_TEST_D8E0YP6XJF
monnify.secret-key=B4KV9KPQPMD1MCZKCA88432DWE6D3GJ9
monnify.contract-code=7886307918

cloudinary.cloud-name=apculh6x
cloudinary.api-key=445615931476397
cloudinary.api-secret=l_GOAtD750cHckAzoEcoa-iFRek