spring.application.name=backend
server.port=8081

spring.docker.compose.enabled=false

monnify.base.url=https://sandbox.monnify.com

monnify.api-key=MK_TEST_D8E0YP6XJF
monnify.secret-key=B4KV9KPQPMD1MCZKCA88432DWE6D3GJ9
monnify.contract-code=7886307918
